// This file was generated by Prisma
import * as dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Load .env file
dotenv.config();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL || "mysql://localhost:3306/database",
  },
});
